### ISSUE TITLE
Faction Gebiet welches mehr kosten soll, falls es nicht angrenzt funktioniert nicht

### ISSUE THREAD

**Issue by Grafe** [DieReicheErethons/FactionsDRE#11]

**Comment by TTTheKing** [comment]
den bug versteh ich nicht... im code wird nur pro angrenzendes land ein counter hochgezählt und schlussendlich abgefragt ob der >0 ist. wieso es dann bei genau 8 angrenzenden chunks spinnt???

**Comment by DieReicheErethons** [comment]
Hmm, ich schaus mir heute auch nochmals genauer an...
