### ISSUE TITLE
Entchantete Items sollen nicht ins obere Inventar gelegt werden können (/f war <faction> additems)

### ISSUE THREAD

**Issue by ghost** [DieReicheErethons/FactionsDRE#8]

**Comment by TTTheKing** [comment]
finde ich zwar überflüssig... das is aber nur meine Meinung.
Hab halt noch bedenken das dadurch bugs, wie zB das man gar keine Enchanteten Items mehr in irgendeinem Inventar anklicken kann, entstehen könnten

**Comment by Grafe** [comment]
Falls man es richtig macht, sollte es auch keine Bugs geben :P
