### ISSUE TITLE
Zeit bis zum Krieg startet den Krieg nicht.

### ISSUE THREAD

**Issue by Grafe** [DieReicheErethons/FactionsDRE#9]

**Comment by Grafe** [comment]
Es startet den Krieg, doch tut es den War nicht updaten.
Bei /f war <faction> kommt dann immer noch "Zeit bis zum Krieg -17h 43m"

**Comment by TTTheKing** [comment]
mhhh die funktion wird nur alle stunde durchgeführt... durch den sheduler

**Comment by TTTheKing** [comment]
so sollte jetzt stimmen hatte auch noch eine Abfrage vergessen sodass immer die zeit angezeigt wurde auch wenn der Krieg eigentlich schon gestartet wäre
